# Define alma_namespaces in common module
alma_namespaces = [
    ("bf", "http://id.loc.gov/ontologies/bibframe/"),
    ("bflc", "http://id.loc.gov/ontologies/bflc/"),
    ("madsrdf", "http://www.loc.gov/mads/rdf/v1#"),
    ("sinopia", "http://sinopia.io/vocabulary/"),
    ("sinopiabf", "http://sinopia.io/vocabulary/bf/"),
    ("rdau", "http://rdaregistry.info/Elements/u/"),
    ("skos", "http://www.w3.org/2004/02/skos/core#"),
    ("dcterms", "http://purl.org/dc/terms/"),
    ("cc", "http://creativecommons.org/ns#"),
    ("foaf", "http://xmlns.com/foaf/0.1/"),
    ("lcill", "http://id.loc.gov/vocabulary/millus/"),
    ("lcmscript", "http://id.loc.gov/vocabulary/mscript/"),
    ("lclang", "https://id.loc.gov/vocabulary/languages/"),
    ("lcmenclvl", "http://id.loc.gov/vocabulary/menclvl/"),
    ("lcvonven", "http://id.loc.gov/vocabulary/descriptionConventions/"),
    ("lchubs", "http://id.loc.gov/resources/hubs/"),
    ("lcnames", "http://id.loc.gov/authorities/names/"),
    ("lcgenre", "http://id.loc.gov/authorities/genreForms/"),
    ("lcorg", "http://id.loc.gov/vocabulary/organizations/"),
    ("lcmsupp", "http://id.loc.gov/vocabulary/msupplcont/"),
    ("lcreal", "http://id.loc.gov/vocabulary/relators/"),
    ("lccontent", "http://id.loc.gov/vocabulary/contentTypes/")]
